git:
  diffRenderers:
    - colorArg: always
      command: delta -s --dark --paging=never --true-color=never --syntax-theme="Catppuccin Mocha"
customCommands:
  - key: 'F'
    command: 'git pull --rebase --autostash'
    context: 'localBranches'
    output: log
